name: Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22  # Use the required Go version

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker_compose.yml up -d 

      - name: Wait for Services to be Ready
        run: sleep 50 

      - name: Run Integration Tests
        run: |
          chmod +x integration_test.sh
          ./integration_test.sh  

      - name: Stop Docker Compose
        run: docker-compose -f docker/docker_compose.yml down
